### ISSUE TITLE
fpDestroyKey and fpDestroyData are called for NULL values in bst_destroy

### ISSUE THREAD

**Issue by yashrk** [AKD92/Search-Tree-Based-Dictionary-ADT#1]
The only check in `bst_destroy()` function in the `bst_init_destroy.c` file is whether `fpDestroyKey` and `fpDestroyData` are set. But in the leafs of the tree (external nodes in the terms you use) you store `NULL` values. So the destructor functions are called for `NULL` values too.

In the example programs you use destruction functions that are doing nothing for `NULL` values. But it isn't a common convention and (if you want to keep that behavior) it must be covered by library documentation, IMO.

The alternative way is to check for `NULL` values in the `bst_destroy()` itself.

**Comment by yashrk** [comment]
> it isn't a common convention

Maybe I was wrong here. It's the standard behavior of the `free()` function, for example. If `NULL` check in the destructor is in fact idiomatic, just close this ticket, please.

**Comment by AKD92** [comment]
>  It's the standard behavior of the `free()` function, for example.

Yes it is, and the standard 'free()' function will execute perfectly for NULL values. Furthermore, the 'fpDestroyKey()' and 'fpDestroyData()' destructor function passed by the caller should conform with the 'free()' function, so that the NULL values wont impose any problem. However I will add a note about this issue at the documentation for better clarity.
